### ISSUE TITLE
Syntax errors

### ISSUE THREAD

**Issue by christianguenter2** [abapGit/abap_git_hosts_apis#3]
![image](https://user-images.githubusercontent.com/17437789/52631487-34bddc80-2ebf-11e9-8c53-9f59e7681f5e.png)

**Comment by larshp** [comment]
yea, I'm messing with it, give me a few hours

**Comment by larshp** [comment]
try again

**Comment by larshp** [comment]
hello world

**Comment by larshp** [comment]
looks okay now, closing
