### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by larshp** [abapGit/abap_git_hosts_apis#6]
add some code to execute unit tests in a package and all subpackages

target:
https://github.com/abapGit/ci_tools/tree/master/src/unit_tests

some inspiration in https://github.com/larshp/abapOpenTest

**Comment by jfilak** [comment]
Is the ADT AUnit HTTP handler good enough?

**Comment by larshp** [comment]
for REST probably yes, but would also like code to trigger it from inside

**Comment by jfilak** [comment]
If only the class CL_AUNIT_ADT_RES_TEST_RUNS was not so REST specific - all the algorithms are there. Hmm, we can wrap it and use it anyways. The method execute_tests is public, so we don't need to try to mimic HTTP.

**Comment by larshp** [comment]
can it also do coverage analysis?
